/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thatguysservice_huami_xdrip_watch_miband_Firmware_operations_AuthOperations2021 */

#ifndef _Included_com_thatguysservice_huami_xdrip_watch_miband_Firmware_operations_AuthOperations2021
#define _Included_com_thatguysservice_huami_xdrip_watch_miband_Firmware_operations_AuthOperations2021
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thatguysservice_huami_xdrip_watch_miband_Firmware_operations_AuthOperations2021
 * Method:    ecdh_lib_get_public_key
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_thatguysservice_huami_1xdrip_watch_miband_Firmware_operations_AuthOperations2021_ecdh_1lib_1get_1public_1key
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_thatguysservice_huami_xdrip_watch_miband_Firmware_operations_AuthOperations2021
 * Method:    ecdh_lib_get_shared_key
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_thatguysservice_huami_1xdrip_watch_miband_Firmware_operations_AuthOperations2021_ecdh_1lib_1get_1shared_1key
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
